API_KEY_GROQ = "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"
API_KEY_DID = "anVhbi5yZW5kb24zNzYzMkB1Y2FsZGFzLmVkdS5jbw:ydxMrcQe23Ay9CbYHcj8u"
URL_BACKEND = "http://127.0.0.1:5000"
MISTRAL_API_KEY = "PAV8MyTnpenBOdF7v7vljd8XtQmWFWIf"